version: '2.0'
services:
  strcpy-fly:
    image: mrjin/shadowsocks:alpine
    container_name: strcpy-fly
    restart: always
    environment:
      - PASSWORD=123456
      - TUN_PORT=15000
    ports:
      - "15000:15000/udp"